# Generated by Django 4.0.3 on 2023-07-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30, null=True)),
                ('Desc', models.TextField()),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('dead', models.DateField()),
            ],
        ),
    ]
